// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type OrderInfo struct {
	Id              int64   `json:"id"`
	OrderNo         string  `json:"orderNo"`
	UserId          int64   `json:"userId"`
	Status          int64   `json:"status"`
	TotalAmount     float64 `json:"totalAmount"`
	DiscountAmount  float64 `json:"discountAmount"`
	PayAmount       float64 `json:"payAmount"`
	PaymentMethod   int64   `json:"paymentMethod"`
	TransactionNo   string  `json:"transactionNo"`
	PaymentTime     string  `json:"paymentTime,optional"`
	ReceiverName    string  `json:"receiverName"`
	ReceiverPhone   string  `json:"receiverPhone"`
	ReceiverAddress string  `json:"receiverAddress"`
	ExpressCompany  string  `json:"expressCompany,optional"`
	ExpressNo       string  `json:"expressNo,optional"`
	Remark          string  `json:"remark"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
}

type SearchRequest struct {
	OrderNo string `form:"orderNo"`
}

type SearchResponse struct {
	OrderInfo OrderInfo `json:"orderInfo"`
	UserName  string    `json:"userName"`
}
