// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ordersFieldNames          = builder.RawFieldNames(&Orders{})
	ordersRows                = strings.Join(ordersFieldNames, ",")
	ordersRowsExpectAutoSet   = strings.Join(stringx.Remove(ordersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ordersRowsWithPlaceHolder = strings.Join(stringx.Remove(ordersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDb1OrdersIdPrefix      = "cache:db1:orders:id:"
	cacheDb1OrdersOrderNoPrefix = "cache:db1:orders:orderNo:"
)

type (
	ordersModel interface {
		Insert(ctx context.Context, data *Orders) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Orders, error)
		FindOneByOrderNo(ctx context.Context, orderNo string) (*Orders, error)
		Update(ctx context.Context, data *Orders) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultOrdersModel struct {
		sqlc.CachedConn
		table string
	}

	Orders struct {
		Id              uint64       `db:"id"` // ID
		OrderNo         string       `db:"order_no"`
		UserId          uint64       `db:"user_id"` // ID
		Status          int64        `db:"status"`  // : 0-, 1-, 2-, 3-, 4-, 5-
		TotalAmount     float64      `db:"total_amount"`
		DiscountAmount  float64      `db:"discount_amount"`
		PayAmount       float64      `db:"pay_amount"`
		PaymentMethod   int64        `db:"payment_method"` // : 0-, 1-, 2-, 3-
		TransactionNo   string       `db:"transaction_no"`
		PaymentTime     sql.NullTime `db:"payment_time"`
		ReceiverName    string       `db:"receiver_name"`
		ReceiverPhone   string       `db:"receiver_phone"`
		ReceiverAddress string       `db:"receiver_address"`
		ExpressCompany  string       `db:"express_company"`
		ExpressNo       string       `db:"express_no"`
		Remark          string       `db:"remark"`
		Version         int64        `db:"version"`
		CreatedAt       time.Time    `db:"created_at"`
		UpdatedAt       time.Time    `db:"updated_at"`
		DeletedAt       sql.NullTime `db:"deleted_at"`
	}
)

func newOrdersModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOrdersModel {
	return &defaultOrdersModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`orders`",
	}
}

func (m *defaultOrdersModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	db1OrdersIdKey := fmt.Sprintf("%s%v", cacheDb1OrdersIdPrefix, id)
	db1OrdersOrderNoKey := fmt.Sprintf("%s%v", cacheDb1OrdersOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, db1OrdersIdKey, db1OrdersOrderNoKey)
	return err
}

func (m *defaultOrdersModel) FindOne(ctx context.Context, id uint64) (*Orders, error) {
	db1OrdersIdKey := fmt.Sprintf("%s%v", cacheDb1OrdersIdPrefix, id)
	var resp Orders
	err := m.QueryRowCtx(ctx, &resp, db1OrdersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ordersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrdersModel) FindOneByOrderNo(ctx context.Context, orderNo string) (*Orders, error) {
	db1OrdersOrderNoKey := fmt.Sprintf("%s%v", cacheDb1OrdersOrderNoPrefix, orderNo)
	var resp Orders
	err := m.QueryRowIndexCtx(ctx, &resp, db1OrdersOrderNoKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `order_no` = ? limit 1", ordersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, orderNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrdersModel) Insert(ctx context.Context, data *Orders) (sql.Result, error) {
	db1OrdersIdKey := fmt.Sprintf("%s%v", cacheDb1OrdersIdPrefix, data.Id)
	db1OrdersOrderNoKey := fmt.Sprintf("%s%v", cacheDb1OrdersOrderNoPrefix, data.OrderNo)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, ordersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OrderNo, data.UserId, data.Status, data.TotalAmount, data.DiscountAmount, data.PayAmount, data.PaymentMethod, data.TransactionNo, data.PaymentTime, data.ReceiverName, data.ReceiverPhone, data.ReceiverAddress, data.ExpressCompany, data.ExpressNo, data.Remark, data.Version, data.DeletedAt)
	}, db1OrdersIdKey, db1OrdersOrderNoKey)
	return ret, err
}

func (m *defaultOrdersModel) Update(ctx context.Context, newData *Orders) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	db1OrdersIdKey := fmt.Sprintf("%s%v", cacheDb1OrdersIdPrefix, data.Id)
	db1OrdersOrderNoKey := fmt.Sprintf("%s%v", cacheDb1OrdersOrderNoPrefix, data.OrderNo)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ordersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.OrderNo, newData.UserId, newData.Status, newData.TotalAmount, newData.DiscountAmount, newData.PayAmount, newData.PaymentMethod, newData.TransactionNo, newData.PaymentTime, newData.ReceiverName, newData.ReceiverPhone, newData.ReceiverAddress, newData.ExpressCompany, newData.ExpressNo, newData.Remark, newData.Version, newData.DeletedAt, newData.Id)
	}, db1OrdersIdKey, db1OrdersOrderNoKey)
	return err
}

func (m *defaultOrdersModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDb1OrdersIdPrefix, primary)
}

func (m *defaultOrdersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ordersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOrdersModel) tableName() string {
	return m.table
}
